# Generated by Django 4.0.3 on 2022-03-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('port', models.CharField(max_length=20)),
                ('protocol', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('anonymity', models.CharField(max_length=20)),
                ('speed', models.CharField(max_length=20)),
                ('uptime', models.CharField(max_length=10, null=True)),
                ('response', models.CharField(max_length=10)),
                ('last_checked', models.CharField(max_length=20)),
            ],
        ),
    ]
