# Generated by Django 4.0.3 on 2022-03-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_scrape', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapejob',
            name='anonymity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='ip',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='last_checked',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='port',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='protocol',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='response',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='speed',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='uptime',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='scrapejob',
            table='proxy',
        ),
    ]
