# Generated by Django 4.0.3 on 2022-03-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_scrape', '0002_alter_scrapejob_anonymity_alter_scrapejob_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapejob',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='last_checked',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='uptime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
